# Generated by Django 3.0.5 on 2023-12-29 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
        migrations.AddField(
            model_name='feedback',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Customer'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='helpful',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedback',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Product'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='feedback',
            name='unhelpful',
            field=models.IntegerField(default=0),
        ),
    ]
