# Generated by Django 3.0.5 on 2023-12-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_auto_20231229_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
