# Generated by Django 3.0.5 on 2023-12-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], default='Women', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='tag1',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='tag2',
            field=models.CharField(default='', max_length=40),
        ),
    ]
