# Generated by Django 3.0.5 on 2024-01-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0013_auto_20240102_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/Screenshot_3.png', upload_to='profile_pic/CustomerProfilePic/'),
        ),
    ]
