# Generated by Django 3.0.5 on 2024-01-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0016_customer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='token',
            field=models.CharField(default='', max_length=200),
        ),
    ]
